-- Seed a broad active country list for Identity / Education dropdowns (defect 1552).
-- Safe to re-run: ON DUPLICATE KEY UPDATE keeps names and marks rows active.

INSERT INTO ref_countries (code, name, postal_regex, active) VALUES
  ('AF', 'Afghanistan', NULL, 1),
  ('AL', 'Albania', NULL, 1),
  ('DZ', 'Algeria', NULL, 1),
  ('AR', 'Argentina', NULL, 1),
  ('AM', 'Armenia', NULL, 1),
  ('AU', 'Australia', '^[0-9]{4}$', 1),
  ('AT', 'Austria', NULL, 1),
  ('AZ', 'Azerbaijan', NULL, 1),
  ('BH', 'Bahrain', NULL, 1),
  ('BD', 'Bangladesh', '^[0-9]{4}$', 1),
  ('BY', 'Belarus', NULL, 1),
  ('BE', 'Belgium', NULL, 1),
  ('BZ', 'Belize', NULL, 1),
  ('BJ', 'Benin', NULL, 1),
  ('BT', 'Bhutan', NULL, 1),
  ('BO', 'Bolivia', NULL, 1),
  ('BA', 'Bosnia and Herzegovina', NULL, 1),
  ('BW', 'Botswana', NULL, 1),
  ('BR', 'Brazil', '^[0-9]{5}-?[0-9]{3}$', 1),
  ('BN', 'Brunei', NULL, 1),
  ('BG', 'Bulgaria', NULL, 1),
  ('KH', 'Cambodia', NULL, 1),
  ('CM', 'Cameroon', NULL, 1),
  ('CA', 'Canada', '^[A-Za-z][0-9][A-Za-z][ ]?[0-9][A-Za-z][0-9]$', 1),
  ('CL', 'Chile', NULL, 1),
  ('CN', 'China', '^[0-9]{6}$', 1),
  ('CO', 'Colombia', NULL, 1),
  ('CR', 'Costa Rica', NULL, 1),
  ('HR', 'Croatia', NULL, 1),
  ('CU', 'Cuba', NULL, 1),
  ('CY', 'Cyprus', NULL, 1),
  ('CZ', 'Czechia', NULL, 1),
  ('DK', 'Denmark', NULL, 1),
  ('DO', 'Dominican Republic', NULL, 1),
  ('EC', 'Ecuador', NULL, 1),
  ('EG', 'Egypt', NULL, 1),
  ('SV', 'El Salvador', NULL, 1),
  ('EE', 'Estonia', NULL, 1),
  ('ET', 'Ethiopia', NULL, 1),
  ('FI', 'Finland', NULL, 1),
  ('FR', 'France', '^[0-9]{5}$', 1),
  ('GE', 'Georgia', NULL, 1),
  ('DE', 'Germany', '^[0-9]{5}$', 1),
  ('GH', 'Ghana', NULL, 1),
  ('GR', 'Greece', NULL, 1),
  ('GT', 'Guatemala', NULL, 1),
  ('HK', 'Hong Kong', NULL, 1),
  ('HU', 'Hungary', NULL, 1),
  ('IS', 'Iceland', NULL, 1),
  ('IN', 'India', '^[1-9][0-9]{5}$', 1),
  ('ID', 'Indonesia', NULL, 1),
  ('IR', 'Iran', NULL, 1),
  ('IQ', 'Iraq', NULL, 1),
  ('IE', 'Ireland', NULL, 1),
  ('IL', 'Israel', NULL, 1),
  ('IT', 'Italy', '^[0-9]{5}$', 1),
  ('JM', 'Jamaica', NULL, 1),
  ('JP', 'Japan', '^[0-9]{3}-?[0-9]{4}$', 1),
  ('JO', 'Jordan', NULL, 1),
  ('KZ', 'Kazakhstan', NULL, 1),
  ('KE', 'Kenya', NULL, 1),
  ('KW', 'Kuwait', NULL, 1),
  ('LV', 'Latvia', NULL, 1),
  ('LB', 'Lebanon', NULL, 1),
  ('LY', 'Libya', NULL, 1),
  ('LT', 'Lithuania', NULL, 1),
  ('LU', 'Luxembourg', NULL, 1),
  ('MO', 'Macao', NULL, 1),
  ('MY', 'Malaysia', NULL, 1),
  ('MV', 'Maldives', NULL, 1),
  ('MT', 'Malta', NULL, 1),
  ('MX', 'Mexico', '^[0-9]{5}$', 1),
  ('MD', 'Moldova', NULL, 1),
  ('MC', 'Monaco', NULL, 1),
  ('MN', 'Mongolia', NULL, 1),
  ('ME', 'Montenegro', NULL, 1),
  ('MA', 'Morocco', NULL, 1),
  ('MZ', 'Mozambique', NULL, 1),
  ('MM', 'Myanmar', NULL, 1),
  ('NP', 'Nepal', NULL, 1),
  ('NL', 'Netherlands', NULL, 1),
  ('NZ', 'New Zealand', NULL, 1),
  ('NG', 'Nigeria', NULL, 1),
  ('MK', 'North Macedonia', NULL, 1),
  ('NO', 'Norway', NULL, 1),
  ('OM', 'Oman', NULL, 1),
  ('PK', 'Pakistan', '^[0-9]{5}$', 1),
  ('PA', 'Panama', NULL, 1),
  ('PY', 'Paraguay', NULL, 1),
  ('PE', 'Peru', NULL, 1),
  ('PH', 'Philippines', NULL, 1),
  ('PL', 'Poland', NULL, 1),
  ('PT', 'Portugal', NULL, 1),
  ('QA', 'Qatar', NULL, 1),
  ('RO', 'Romania', NULL, 1),
  ('RU', 'Russia', NULL, 1),
  ('SA', 'Saudi Arabia', NULL, 1),
  ('RS', 'Serbia', NULL, 1),
  ('SG', 'Singapore', '^[0-9]{6}$', 1),
  ('SK', 'Slovakia', NULL, 1),
  ('SI', 'Slovenia', NULL, 1),
  ('ZA', 'South Africa', NULL, 1),
  ('KR', 'South Korea', NULL, 1),
  ('ES', 'Spain', '^[0-9]{5}$', 1),
  ('LK', 'Sri Lanka', NULL, 1),
  ('SE', 'Sweden', NULL, 1),
  ('CH', 'Switzerland', NULL, 1),
  ('SY', 'Syria', NULL, 1),
  ('TW', 'Taiwan', NULL, 1),
  ('TZ', 'Tanzania', NULL, 1),
  ('TH', 'Thailand', NULL, 1),
  ('TT', 'Trinidad and Tobago', NULL, 1),
  ('TN', 'Tunisia', NULL, 1),
  ('TR', 'Turkey', NULL, 1),
  ('UG', 'Uganda', NULL, 1),
  ('UA', 'Ukraine', NULL, 1),
  ('AE', 'United Arab Emirates', '^[0-9]{5}$', 1),
  ('GB', 'United Kingdom', '^(GIR 0AA|[A-Za-z]{1,2}[0-9][A-Za-z0-9]? [0-9][A-Za-z]{2})$', 1),
  ('US', 'United States', '^[0-9]{5}(-[0-9]{4})?$', 1),
  ('UY', 'Uruguay', NULL, 1),
  ('UZ', 'Uzbekistan', NULL, 1),
  ('VE', 'Venezuela', NULL, 1),
  ('VN', 'Vietnam', NULL, 1),
  ('YE', 'Yemen', NULL, 1),
  ('ZM', 'Zambia', NULL, 1),
  ('ZW', 'Zimbabwe', NULL, 1) AS new_rows
ON DUPLICATE KEY UPDATE
  name = new_rows.name,
  postal_regex = COALESCE(new_rows.postal_regex, ref_countries.postal_regex),
  active = 1;
